### ISSUE TITLE
--dos2unix doesn't replace full path

### ISSUE THREAD

**Issue by emuspawn** [kgarner7/navidrome-migrate#3]
I have my music in artist folders, as in /mnt/media/music/artist/song.mp3. The --dos2unix command only appears to try and replace the first slash in the path. I've currently moved my files to the new location as specified by the README.

Running the command  python3 migrate.py navidrome.db  'D:\Emerald Roost Data\Music\' '/mnt/media/music/' generates the following error:
Traceback (most recent call last):
  File "/var/lib/navidrome/migrate.py", line 171, in <module>
    raise Exception(
Exception: Could not find a file at '/mnt/media/music/(1999) 69 Love Songs\69 Love Songs (Volume I)\Magnetic Fields - 01 - Absolutely Cuckoo.mp3'. Please make sure the new path is correct
ERROR: Could not find a file at '/mnt/media/music/(1999) 69 Love Songs\69 Love Songs (Volume I)\Magnetic Fields - 01 - Absolutely Cuckoo.mp3'. Please make sure the new path is correct

**Comment by kgarner7** [comment]
Resolved by https://github.com/kgarner7/navidrome-migrate/commit/bcd4d0b11291c3cea2551a20bde1ca876c51161d
